# Plex - Media Server
version: '2'
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    restart: unless-stopped
    networks:
      - default
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    
    environment:
      TZ: $TZ
      HOSTNAME: "dockerPlex"
      PLEX_CLAIM: $PLEX_CLAIM
      PLEX_UID: $PUID
      PLEX_GID: $PGID
        #ADVERTISE_IP: http://$SERVER_IP:32400/
        #ALLOWED_NETWORKS: $LOCAL_NETWORK
    hostname: plexserver.example.com
    volumes:
      - ./data/plex/database:/config
      - ./data/plex/transcode:/transcode
      - /media/oem/NewVolume:/data
